import { MigrationInterface, QueryRunner } from "typeorm";

export class init1669772861180 implements MigrationInterface {
    name = '1669772861180'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "estado_cargo" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "descripcion" character varying(255) NOT NULL, "esVacancia" boolean NOT NULL, "esInicial" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_21c6a7fbad04c6eef1b64f4f41a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "departamento_judicial" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "descripcion" character varying(255) NOT NULL, CONSTRAINT "PK_eae0545f3987aa9b46e2c65d49a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fuero" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "descripcion" character varying(255) NOT NULL, CONSTRAINT "PK_b6fdc2ae6c617c44f5c9cfdc4e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organismo_jurisdiccional" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "descripcion" character varying(255) NOT NULL, CONSTRAINT "PK_e966a7b7befadcdc8819b72a4d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tipo_cargo" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "descripcion" character varying(255) NOT NULL, CONSTRAINT "PK_31d90a6ef06548e1af37c158190" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cargo" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "funciona" boolean NOT NULL DEFAULT true, "numero" integer, "sede" character varying(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAd" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tipoCargoId" integer NOT NULL, "fueroId" integer NOT NULL, "departamentoJudicialId" integer NOT NULL, "organismoJurisdiccionalId" integer NOT NULL, "estadoCargoId" integer NOT NULL, CONSTRAINT "PK_1af8b2a790f35aedbe7e3da4199" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "cargo" ADD CONSTRAINT "FK_edd04e29591b8a85176eb930e04" FOREIGN KEY ("tipoCargoId") REFERENCES "tipo_cargo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo" ADD CONSTRAINT "FK_17ce125786fd8513eeeb7e6e5ca" FOREIGN KEY ("fueroId") REFERENCES "fuero"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo" ADD CONSTRAINT "FK_54db43d9d5b25ce5d7ceaa81c4c" FOREIGN KEY ("departamentoJudicialId") REFERENCES "departamento_judicial"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo" ADD CONSTRAINT "FK_b617f2c689618130b79e6a654e9" FOREIGN KEY ("organismoJurisdiccionalId") REFERENCES "organismo_jurisdiccional"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cargo" ADD CONSTRAINT "FK_ede418b18228adac7bb83d474c4" FOREIGN KEY ("estadoCargoId") REFERENCES "estado_cargo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cargo" DROP CONSTRAINT "FK_ede418b18228adac7bb83d474c4"`);
        await queryRunner.query(`ALTER TABLE "cargo" DROP CONSTRAINT "FK_b617f2c689618130b79e6a654e9"`);
        await queryRunner.query(`ALTER TABLE "cargo" DROP CONSTRAINT "FK_54db43d9d5b25ce5d7ceaa81c4c"`);
        await queryRunner.query(`ALTER TABLE "cargo" DROP CONSTRAINT "FK_17ce125786fd8513eeeb7e6e5ca"`);
        await queryRunner.query(`ALTER TABLE "cargo" DROP CONSTRAINT "FK_edd04e29591b8a85176eb930e04"`);
        await queryRunner.query(`DROP TABLE "cargo"`);
        await queryRunner.query(`DROP TABLE "tipo_cargo"`);
        await queryRunner.query(`DROP TABLE "organismo_jurisdiccional"`);
        await queryRunner.query(`DROP TABLE "fuero"`);
        await queryRunner.query(`DROP TABLE "departamento_judicial"`);
        await queryRunner.query(`DROP TABLE "estado_cargo"`);
    }

}
